### ISSUE TITLE
Every sync failed after upgraded bazel plugin in CLion

### ISSUE THREAD

**Issue by erinacio** [bazelbuild/intellij#4965]
### Description of the bug:

After upgrading Bazel for CLion to `2023.05.30.0.1-api-version-231`, all bazel sync failed with "Sync finished with errors", like:

```
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no --
Computing VCS working set...
17:56:42	Initial directory update started
17:56:42	Initial directory update finished
17:56:42	Sync started
17:56:43	Sync finished with errors
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a simplist Bazel C++ project and try to sync it with Bazel for CLion.

<details><summary>WORKSPACE</summary>

```
workspace(name = "bzlexp")
```

</details>

<details><summary>BUILD.bazel</summary>

```
cc_binary(
    name = "main",
    srcs = ["main.cc"],
)
```

</details>

<details><summary>main.cc</summary>

```
int main() {
    return 0;
}
```

</details>

<details><summary>.clwb/.bazelproject</summary>

```yaml
directories:
  .

# Automatically includes all relevant targets under the 'directories' above
derive_targets_from_directories: true

targets:
  # If source code isn't resolving, add additional targets that compile it here

additional_languages:
  # Uncomment any additional languages you want supported
  # dart
  # javascript
  # python
  # typescript
```

</details>

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.1.3, Build #CL-231.9011.31, built on May 16, 2023

### What programming languages and tools are you using? Please provide specific versions.

C++, clang 15.0.7

### What Bazel plugin version are you using?

2023.05.30.0.1-api-version-231

### Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

I added several lines exporting some environment variables to the CLion startup script but I don't think they're relevant, as older bazel plugins didn't fail with these environment variables.

```bash
export CC=/opt/llvm15/bin/clang
export CXX=/opt/llvm15/bin/clang++
export PATH=/opt/llvm15/bin:$PATH
export LD_LIBRARY_PATH=/opt/llvm15/lib:/opt/llvm15/lib/x86_64-unknown-linux-gnu
export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
```

Clearing cache doesn't help.

Changing bazel version doesn't help. I tried 5.1.1, 6.1.1 and 6.2.0, none of them works.

New files added to the project will no longer be marked "unsynced" after a sync, but files from external projects are not properly synced. Only saw `bazel_tools` in `bazel-<upperfoldername>/external` directory.
