### ISSUE TITLE
Source jars of java_library targets are not attached

### ISSUE THREAD

**Issue by keithkml** [bazelbuild/intellij#500]
Using version 2018.12.03, on Bazel 0.20, we do not get any source jars for `java_library` targets. I've included the `intellij-info.txt` for one example.

The full output is below. The source jar we wish was attached is `libcore-src.jar`, which is present on disk at `$(WORKSPACE)/bazel-bin/core/libcore-src.jar`
(which is right alongside the header jar that IntelliJ *does* pick up, which is `$(WORKSPACE)/bazel-bin/core/libcore-hjar.jar`).

```yaml
build_file_artifact_location {
  is_external: false
  is_new_external_version: true
  is_source: true
  relative_path: "core/java/BUILD"
  root_execution_path_fragment: ""
}
deps {
  dependency_type: 0
  target {
    label: "//build/bazel:toolchain_jdk8"
  }
}
deps {
  dependency_type: 0
  target {
    label: "//ext/public/google/guava/19/0:jars"
  }
}
deps {
  dependency_type: 0
  target {
    label: "(redacted)"
  }
}
deps {
  dependency_type: 0
  target {
    label: "@com_google_protobuf//:jars"
  }
}
java_ide_info {
  jars {
    interface_jar {
      is_external: false
      is_new_external_version: true
      is_source: false
      relative_path: "core/java/libcore-hjar.jar"
      root_execution_path_fragment: "bazel-out/k8-opt/bin"
    }
    jar {
      is_external: false
      is_new_external_version: true
      is_source: false
      relative_path: "core/java/libcore.jar"
      root_execution_path_fragment: "bazel-out/k8-opt/bin"
    }
    source_jar {
      is_external: false
      is_new_external_version: true
      is_source: false
      relative_path: "core/java/libcore-src.jar"
      root_execution_path_fragment: "bazel-out/k8-opt/bin"
    }
    source_jars {
      is_external: false
      is_new_external_version: true
      is_source: false
      relative_path: "core/java/libcore-src.jar"
      root_execution_path_fragment: "bazel-out/k8-opt/bin"
    }
  }
  jdeps {
    is_external: false
    is_new_external_version: true
    is_source: false
    relative_path: "core/java/libcore.jdeps"
    root_execution_path_fragment: "bazel-out/k8-opt/bin"
  }
  package_manifest {
    is_external: false
    is_new_external_version: true
    is_source: false
    relative_path: "core/java/core.java-manifest"
    root_execution_path_fragment: "bazel-out/k8-opt/bin"
  }
  sources {
    is_external: false
    is_new_external_version: true
    is_source: true
    relative_path: "core/java/src/core/<redacted>.java"
    root_execution_path_fragment: ""
  }
  sources {
    is_external: false
    is_new_external_version: true
    is_source: true
    relative_path: "core/java/src/core/<redacted>.java"
    root_execution_path_fragment: ""
  }
  sources {
    is_external: false
    is_new_external_version: true
    is_source: true
    relative_path: "core/java/src/core/<redacted>.java"
    root_execution_path_fragment: ""
  }
}
key {
  label: "//core/java:core"
}
kind_string: "java_library"
```
