### ISSUE TITLE
Ray Code cannot be recognized in CLion.

### ISSUE THREAD

**Issue by louj1988** [bazelbuild/intellij#6389]
#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

Recently, I've been studying and researching Ray, which is a project built with Bazel. I've installed Bazel locally, and I can compile successfully. However, when using CLion Bazel project, the code is not recognized. I've tried options in the Bazel plugin menu, but they didn't work.

![image](https://github.com/bazelbuild/intellij/assets/167095048/65005fc4-84dd-4b7e-aca9-9e82ba281c34)

#### Version information
CLion: 2024.1
Platform: Mac OS X 14.1
Bazel for CLion plugin: 2024.03.26.0.1-api-version-241
Bazel: 5.4.1

**Comment by louj1988** [comment]
Clion can't seem to get it recognized. Any suggestions?

**Comment by LeFrosch** [comment]
Hi @louj1988, thanks for sharing this issue. I am assuming you are trying to edit the ray source code using CLion. However, I was not able to reproduce your issue. Could you maybe share your project view file? You can find this file under Bazel -> Project -> Open Project View File. 
Also I noticed that syncing the entire project yields many errors. Maybe a more restricted view could help. You can try restricting the bazel plugin to only the source directory using the project view file:
```yaml
directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  
  # Add the next line to your project view file
  src 

# Automatically includes all relevant targets under the 'directories' above
derive_targets_from_directories: true

targets:
  # If source code isn't resolving, add additional targets that compile it here

additional_languages:
  # Uncomment any additional languages you want supported
  # dart
  # javascript
  # python
  # typescript
```
